## This program to run wordpress

--- 
- hosts: test
  become: yes
  vars:
    database_name_here: wordpress
    username_here: wordpress
    password_here: mypasswd1
    dbhost_here: sourav_test

  tasks:
  - name: Install php for wordpress
    yum: name={{ item }} 
    with_items:
       - php
       - php-gd
       - php-pear
       - php-mysql

  - name: restart httpd
    service: name=httpd state=restarted

  - unarchive: 
      src: https://wordpress.org/latest.tar.gz
      dest: /tmp/
      remote_src: True

  - name: Remove html folder
    command: /usr/bin/rm -rf /var/www/html
 
  - name: Move folder
    command: /usr/bin/mv /tmp/wordpress /var/www/html

  - name: Copy template to host
    template: src=wp.config.j2 dest=/var/www/html/wp.config.php  ##File "wp.config.j2" is present under the downloaded wordpress directory
