# Command :- ansible-playbook -i hosts debg.yml -k -K -s

---    # Playbook demo of debug and register statement.

- hosts: test
  remote_user: shourabh
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no

  tasks:
  - name: Installing telnet package
    yum:
      name: telnet
      state: latest
    register: result     # Register the result of that module's output in some variable called "result".
  - debug: var=result    # debug module to display my variable named "result". 

    
  
