##This program is to install multiple packages

---
- hosts: test
  become: yes
  become_method: sudo
  tasks:
  - name: Install multiple packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - httpd
      - vim
      - telnet
