---
- hosts: test
  become: yes
  become_method: sudo
  
  tasks:
  - name: Install apache
    yum:
      name: httpd
      state: latest

  - name: Create a file if it doesn't exists
    file:
      state: touch
      path: /var/www/html/index.html
      mode: 750

  - name: If the line not there then add it
    lineinfile:
      state: present
      dest: /var/www/html/index.html
      line: Hostname={{ ansible_hostname }}

  - name: Restart apache
    service:
      name: httpd
      state: reloaded
      enable: yes
    
       
