# Run this playbook using below command to avoid error.
# ansible-playbook -i hosts varstruc.yml --extra-var "myvars=test gather=yes pkg=telnet" -k -K -s


---     # Testing how variables works in the variable section of the playbook.

- hosts: '{{ myvars }}'
  user: shourabh
  sudo: yes
#  become: yes
#  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  vars: 
#    myvars: test
#    gather: yes
#    pkg: telnet
 
  tasks:
  - name: Install the indicated package
    yum: name='{{ pkg }}' state=latest

