---
- hosts: webservers
  remote_user: shourabh
  sudo: yes
#  gather_facts: yes
  vars: 
    http_port: 80
    max_clients: 200
  
  tasks:
  - name: Ensure apache is at latest verison
    yum: name=httpd state=latest
  - name: Write apache config file
    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
    notify:
    - Restart apache
  - name: Ensure apache is running ( and enable it at root)
    service: name=httpd state=started enabled=yes

  handlers:
  - name: Restart apache
    service: name=httpd state=restarted  
